// This file configures the development web server
// which supports hot reloading and synchronized testing.

// Require Browsersync along with webpack and middleware for it
import browserSync from "browser-sync";
// Required for react-router browserHistory
// see https://github.com/BrowserSync/browser-sync/issues/204#issuecomment-102623643
import historyApiFallback from "connect-history-api-fallback";
import webpack from "webpack";
import webpackDevMiddleware from "webpack-dev-middleware";
import webpackHotMiddleware from "webpack-hot-middleware";
import config from "../webpack.config.dev";

const bundler = webpack(config);

// Create webpack middleware
const webpackMiddleware = webpackDevMiddleware(bundler, {
	// Dev middleware can"t access config, so we provide publicPath
	publicPath: config.output.publicPath,
	stats: {
		assets: true,
		colors: true,
		version: false,
		hash: false,
		timings: true,
		chunks: false,
		chunkModules: false
	},
	writeToDisk: false,
	// Serve index.html for all routes
	index: 'index.html',
	// for other settings see
	// http://webpack.github.io/docs/webpack-dev-middleware.html
});

// Track if BrowserSync has been initialized
let bsInitialized = false;

// Custom middleware to ensure root path is handled by webpack
const rootPathHandler = (req, res, next) => {
	// If requesting root, rewrite to index.html so webpack middleware can serve it
	if (req.url === '/' || req.url === '') {
		req.url = '/index.html';
	}
	next();
};

// Log webpack compilation status
bundler.hooks.done.tap('WebpackInfo', (stats) => {
	if (stats.hasErrors()) {
		console.error('Webpack compilation errors:', stats.compilation.errors);
	}
	if (stats.hasWarnings()) {
		console.warn('Webpack compilation warnings:', stats.compilation.warnings);
	}
});

// Start BrowserSync immediately - webpack middleware will handle requests
// The middleware will wait for compilation to complete before serving
if (!bsInitialized) {
	bsInitialized = true;
	console.log('Starting BrowserSync server on http://localhost:3001');
	
	// Run Browsersync and use middleware for Hot Module Replacement
	browserSync({
		port: 3001,
		ui: {
			port: 3002
		},
		server: {
			baseDir: ["src"], // Fallback for static assets only (CSS, images, etc.)
			middleware: [
				// Custom handler to rewrite root path to index.html
				rootPathHandler,
				// webpack dev middleware serves the bundle and HTML from memory
				// It will serve the index.html generated by HtmlWebpackPlugin
				webpackMiddleware,
				// webpack hot middleware for hot module replacement
				webpackHotMiddleware(bundler),
				// historyApiFallback for React Router - redirects all routes to index.html
				historyApiFallback({
					index: '/index.html',
					disableDotRule: true,
					htmlAcceptHeaders: ['text/html', 'application/xhtml+xml']
				})
			]
		},
		
		// no need to watch "*.js" here, webpack will take care of it for us,
		// including full page reloads if HMR won"t work
		files: [
			"src/*.html"
		],
		
		// Don't open browser automatically
		open: false,
		
		// Log level
		logLevel: "info",
		logPrefix: "BS",
		logConnections: false,
		logFileChanges: true
	});
}
